import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "../styles/Home.module.css";
import nextPackage from "next/package.json";

export async function getStaticProps(ctx) {
  return {
    props: {},
  };
}

export default function Home({}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js with bun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello</h1>
    </div>
  );
}
